version: '3'
services:
  
  petclinic:
    build:
      context: .
    entrypoint: bash -c "/wait-for-it.sh -h mysql -p 3306 -- java -Dspring.datasource.url=jdbc:mysql://mysql:3306/petclinic?enabledTLSProtocols=TLSv1.2 -Dspring.datasource.username=pc -Dspring.jpa.hibernate.ddl-auto=update -Dspring.jpa.database-platform=org.hibernate.dialect.MySQL57Dialect -cp /app/resources:/app/classes:/app/libs/* org.springframework.samples.petclinic.PetClinicApplication"
    ports:
      - "9966"
    environment:
      - "SPRING_PROFILES_ACTIVE=mysql,spring-data-jpa"
    depends_on:
      - mysql
      
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=pc
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic

